services:

  ### database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  ### jvm
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8888:8888"
#    depends_on:
#      - postgres
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
#      DB_NAME: ${DB_NAME}
#      DB_SCHEMA: ${DB_SCHEMA}
#      SERVER_PORT: 8888
#      JWT_SECRET: ${JWT_SECRET}
#      JWT_TTL: ${JWT_TTL}
