spring:
  application:
    name: book-catalog
    version: '@project.version@'
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:mem:bookstore
    username: sa
    password: pass
    driver-class-name: org.h2.Driver

  liquibase:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full

server:
  port: 18888
  servlet:
    context-path: /${spring.application.name}
  error:
    whitelabel:
      enabled: false
