spring:
  application:
    name: book-store-data-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        default_schema: ${DB_SCHEMA}

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${SERVER_PORT_DATA}
  servlet:
    context-path: /${spring.application.name}
