spring:
  application.name: book-store-facade-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${SERVER_PORT_FACADE}
  servlet.context-path: /${spring.application.name}

data-service:
  author.url: ${DATA_URL}/book-store-data-service/v1/author
  book.url: ${DATA_URL}/book-store-data-service/v1/book
  store.url: ${DATA_URL}/book-store-data-service/v1/store
  user.url: ${DATA_URL}/book-store-data-service/v1/users

jwt.secret: ${JWT_SECRET}
jwt.expiration: ${JWT_EXPIRATION_SEC}
