@id=0194f161-5c42-7958-8915-7cf7496d4b00

### GET authors
GET {{facade-url}}/v1/author
Authorization: Bearer {{user-jwt}}

### GET author by ID
GET {{facade-url}}/v1/author/{{id}}
Authorization: Bearer {{user-jwt}}

###