name: "Docker Build"

on:
  workflow_run:
    workflows: ["Maven Build"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts from Maven workflow
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Maven Build
          run_id: ${{ github.event.workflow_run.id }}
          name: app.jar
          path: target

      - name: Download artifact for manual run
        if: github.event_name == 'workflow_dispatch'
        uses: actions/download-artifact@v4
        with:
          name: app.jar
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build JVM Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: book-catalog-service:latest
          outputs: type=docker,dest=/tmp/book-catalog-service.tar

      - name: Upload Docker image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/book-catalog-service.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image from artifact
        run: docker load --input /tmp/book-catalog-service.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag book-catalog-service:latest ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
