name: Test and Build Snapshot

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  maven-verify:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Verify book-store-data
        run: mvn -B clean verify --file book-store-data/pom.xml

      - name: Verify book-store-facade
        run: mvn -B clean verify --file book-store-facade/pom.xml

  maven-build:
    needs: maven-verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Build book-store-data
        run: mvn -B package --file book-store-data/pom.xml

      - name: Build book-store-facade
        run: mvn -B package --file book-store-facade/pom.xml

      - name: Upload book-store-data JAR
        uses: actions/upload-artifact@v4
        with:
          name: book-store-data.jar
          path: book-store-data/target/*.jar

      - name: Upload book-store-facade JAR
        uses: actions/upload-artifact@v4
        with:
          name: book-store-facade.jar
          path: book-store-facade/target/*.jar

  docker-build-push:
    needs: maven-build
    runs-on: ubuntu-latest
    env:
      CURRENT_VERSION: ''

    steps:
      - uses: actions/checkout@v4

      - name: Download book-store-data JAR
        uses: actions/download-artifact@v4
        with:
          name: book-store-data.jar

      - name: Download book-store-facade JAR
        uses: actions/download-artifact@v4
        with:
          name: book-store-facade.jar

      - name: Move JAR files to /app
        run: |
          mv book-store-data.jar ./book-store-data/target/data-app.jar
          mv book-store-facade.jar ./book-store-facade/target/facade-app.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Get Version
        run: echo "CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build Docker image for book-store-data
        uses: docker/build-push-action@v6
        with:
          context: book-store-data
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/book-store-data:${{ env.CURRENT_VERSION }}-${{ github.run_id }}

      - name: Build Docker image for book-store-facade
        uses: docker/build-push-action@v6
        with:
          context: book-store-facade
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/book-store-facade:${{ env.CURRENT_VERSION }}-${{ github.run_id }}
